#!/usr/bin/env bash
# Golden image catalog: validate [file] | generate | check. images/catalog.yaml is the source of the
# Kyverno params ConfigMap and the catalog doc; check reports drift without rewriting either file.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CATALOG="$REPO_ROOT/images/catalog.yaml"
PARAMS_CONFIGMAP=policies/params/golden-images.yaml
CATALOG_DOC=docs/golden-images.md
FIELDS='["digest","eol","name","released","status","version"]'

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

# Prints one error line per defect of catalog $1; exits non-zero when there is one.
validate() {
  local file="$1" json errors=() i count label name version digest status field value
  [ -f "$file" ] || die "$file: catalog not found"
  json="$(yq -o=json '.' "$file" 2>&1)" || die "$file: not valid YAML: $json"
  jq -e 'type == "object" and (.images | type == "array") and (.images | length > 0)' <<<"$json" >/dev/null ||
    die "$file: images: must be a non-empty list"

  count="$(jq '.images | length' <<<"$json")"
  for ((i = 0; i < count; i++)); do
    label="$file: images[$i]"
    if ! jq -e ".images[$i] | type == \"object\"" <<<"$json" >/dev/null; then
      errors+=("$label: must be a mapping")
      continue
    fi
    while IFS= read -r field; do
      errors+=("$label: $field: missing")
    done < <(jq -r --argjson f "$FIELDS" "\$f - (.images[$i] | keys) | .[]" <<<"$json")
    while IFS= read -r field; do
      errors+=("$label: $field: unknown field")
    done < <(jq -r --argjson f "$FIELDS" "(.images[$i] | keys) - \$f | .[]" <<<"$json")
    # Every present field must be a YAML string (dates quoted, so they stay YYYY-MM-DD text).
    while IFS= read -r field; do
      errors+=("$label: $field: must be a quoted string")
    done < <(yq -r ".images[$i] | to_entries[] | select(.value | tag != \"!!str\") | .key" "$file")

    name="$(jq -r ".images[$i].name // \"\" | tostring" <<<"$json")"
    version="$(jq -r ".images[$i].version // \"\" | tostring" <<<"$json")"
    digest="$(jq -r ".images[$i].digest // \"\" | tostring" <<<"$json")"
    status="$(jq -r ".images[$i].status // \"\" | tostring" <<<"$json")"
    [[ "$name" =~ ^[a-z0-9-]+$ ]] || errors+=("$label: name: '$name' is not [a-z0-9-]+")
    [ -n "$version" ] || errors+=("$label: version: must not be empty")
    if jq -e ".images[$i] | has(\"digest\")" <<<"$json" >/dev/null; then
      [[ "$digest" =~ ^sha256:[0-9a-f]{64}$ ]] || errors+=("$label: digest: '$digest' is not sha256:<64 lowercase hex>")
    fi
    if jq -e ".images[$i] | has(\"status\")" <<<"$json" >/dev/null; then
      [[ "$status" =~ ^(supported|deprecated|eol)$ ]] || errors+=("$label: status: '$status' is not supported|deprecated|eol")
    fi
    for field in released eol; do
      jq -e ".images[$i] | has(\"$field\")" <<<"$json" >/dev/null || continue
      value="$(jq -r ".images[$i].$field | tostring" <<<"$json")"
      # A real calendar day: GNU date rejects 2027-02-30 and the round trip rejects other forms.
      if [[ ! "$value" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] ||
        [ "$(date -u -d "$value" +%F 2>/dev/null)" != "$value" ]; then
        errors+=("$label: $field: '$value' is not a YYYY-MM-DD calendar day")
      fi
    done
  done

  # ConfigMap keys are derived from digests: two entries cannot share one.
  while IFS= read -r digest; do
    errors+=("$file: digest: $digest appears in more than one entry")
  done < <(jq -r '[.images[] | objects | .digest | strings] | group_by(.) | map(select(length > 1) | .[0]) | .[]' <<<"$json")

  if [ "${#errors[@]}" -gt 0 ]; then
    printf 'ERROR: %s\n' "${errors[@]}" >&2
    return 1
  fi
}

# Writes the generated files from the catalog into directory $1.
render() {
  local out="$1" name version digest status released eol
  mkdir -p "$out/$(dirname "$PARAMS_CONFIGMAP")" "$out/$(dirname "$CATALOG_DOC")"
  {
    printf '# Generated by `task catalog:generate` from images/catalog.yaml: do not edit.\n'
    printf 'apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: golden-images\n  namespace: kyverno\ndata:\n'
    while IFS=$'\t' read -r name version digest status released eol; do
      printf '  sha256.%s: %s\n' "${digest#sha256:}" "$status"
    done < <(yq -r '.images[] | [.name, .version, .digest, .status, .released, .eol] | @tsv' "$CATALOG")
  } >"$out/$PARAMS_CONFIGMAP"
  {
    printf '<!-- Generated by `task catalog:generate` from images/catalog.yaml: do not edit. -->\n'
    printf '# Golden images\n\n'
    printf 'Images published at `ghcr.io/naqa92-portfolio-projects/harborlab/golden/<name>` and replicated\n'
    printf 'to `harbor.127.0.0.1.nip.io/golden/<name>`. Admission accepts `supported` bases, warns on\n'
    printf '`deprecated` ones and denies `eol` or unknown ones.\n\n'
    printf '| Name | Version | Digest | Status | Released | EOL |\n'
    printf '|---|---|---|---|---|---|\n'
    while IFS=$'\t' read -r name version digest status released eol; do
      printf '| %s | %s | `%s` | %s | %s | %s |\n' "$name" "${version//|/\\|}" "$digest" "$status" "$released" "$eol"
    done < <(yq -r '.images[] | [.name, .version, .digest, .status, .released, .eol] | @tsv' "$CATALOG")
  } >"$out/$CATALOG_DOC"
}

[ "$#" -ge 1 ] || die "usage: $0 validate [catalog file] | generate | check"
case "$1" in
  validate)
    validate "${2:-$CATALOG}"
    echo "${2:-$CATALOG}: valid"
    ;;
  generate)
    validate "$CATALOG"
    render "$REPO_ROOT"
    echo "generated $PARAMS_CONFIGMAP and $CATALOG_DOC"
    ;;
  check)
    validate "$CATALOG"
    work="$(mktemp -d)"
    trap 'rm -rf "$work"' EXIT
    render "$work"
    drift=0
    for file in "$PARAMS_CONFIGMAP" "$CATALOG_DOC"; do
      if ! diff -u --label "$file (committed)" --label "$file (generated)" "$REPO_ROOT/$file" "$work/$file" 2>&1; then
        drift=1
      fi
    done
    [ "$drift" -eq 0 ] || die "generated files are out of date: run task catalog:generate"
    echo "generated files match images/catalog.yaml"
    ;;
  *) die "usage: $0 validate [catalog file] | generate | check" ;;
esac
