apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.29.1
  ignoreDifferences:
    {{- toYaml .Values.webhookCaBundleDifferences | nindent 4 }}
  syncPolicy:
    {{- toYaml .Values.syncPolicy | nindent 4 }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
