apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.11.0
  ignoreDifferences:
    {{- toYaml .Values.webhookCaBundleDifferences | nindent 4 }}
  syncPolicy:
    {{- toYaml .Values.syncPolicy | nindent 4 }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
